// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubastaYa.Api.Data;

#nullable disable

namespace SubastaYa.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906221444_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SubastaYa.Api.Models.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntidadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("SubastaYa.Api.Models.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SaldoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Billeteras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SaldoRetenido = 0m,
                            SaldoTotal = 0m,
                            UsuarioId = 1,
                            Version = 0
                        },
                        new
                        {
                            Id = 2,
                            SaldoRetenido = 45000m,
                            SaldoTotal = 150000m,
                            UsuarioId = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            SaldoRetenido = 0m,
                            SaldoTotal = 200000m,
                            UsuarioId = 3,
                            Version = 0
                        },
                        new
                        {
                            Id = 4,
                            SaldoRetenido = 0m,
                            SaldoTotal = 500m,
                            UsuarioId = 4,
                            Version = 0
                        });
                });

            modelBuilder.Entity("SubastaYa.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlIcono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Coleccionables"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Indumentaria"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vehículos"
                        });
                });

            modelBuilder.Entity("SubastaYa.Api.Models.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompradorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPuja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubastaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("SubastaId");

                    b.ToTable("Pujas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompradorId = 3,
                            FechaPuja = new DateTime(2026, 9, 6, 21, 34, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            Monto = 32000m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompradorId = 2,
                            FechaPuja = new DateTime(2026, 9, 6, 21, 54, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            Monto = 45000m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompradorId = 3,
                            FechaPuja = new DateTime(2026, 9, 5, 22, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            Monto = 9500m,
                            SubastaId = 4
                        });
                });

            modelBuilder.Entity("SubastaYa.Api.Models.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VendedorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Subastas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Activa estándar, con 2 pujas previas.",
                            Estado = 1,
                            FechaFin = new DateTime(2026, 9, 6, 22, 39, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            FechaInicio = new DateTime(2026, 9, 6, 21, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            IncrementoMinimo = 1000m,
                            PrecioBase = 30000m,
                            Titulo = "Notebook Gamer RTX",
                            UrlImagen = "https://picsum.photos/seed/notebook/400/300",
                            VendedorId = 1,
                            Version = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Activa crítica: cierra en menos de 2 minutos, para probar anti-sniping.",
                            Estado = 1,
                            FechaFin = new DateTime(2026, 9, 6, 22, 19, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            FechaInicio = new DateTime(2026, 9, 6, 20, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            IncrementoMinimo = 500m,
                            PrecioBase = 5000m,
                            Titulo = "Figura de colección edición limitada",
                            UrlImagen = "https://picsum.photos/seed/figura/400/300",
                            VendedorId = 1,
                            Version = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 4,
                            Descripcion = "Próxima: inicio programado a +24hs, pujas bloqueadas.",
                            Estado = 0,
                            FechaFin = new DateTime(2026, 9, 8, 22, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            FechaInicio = new DateTime(2026, 9, 7, 22, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            IncrementoMinimo = 10000m,
                            PrecioBase = 800000m,
                            Titulo = "Moto 150cc",
                            UrlImagen = "https://picsum.photos/seed/moto/400/300",
                            VendedorId = 1,
                            Version = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            Descripcion = "Vencida con ganador: para probar cierre y liquidación del Worker.",
                            Estado = 1,
                            FechaFin = new DateTime(2026, 9, 6, 22, 4, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            FechaInicio = new DateTime(2026, 9, 4, 22, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            IncrementoMinimo = 500m,
                            PrecioBase = 8000m,
                            Titulo = "Campera de cuero vintage",
                            UrlImagen = "https://picsum.photos/seed/campera/400/300",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            Descripcion = "Vencida desierta: sin pujas, para probar pase a DESIERTA.",
                            Estado = 1,
                            FechaFin = new DateTime(2026, 9, 6, 22, 9, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            FechaInicio = new DateTime(2026, 9, 4, 22, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            IncrementoMinimo = 200m,
                            PrecioBase = 3000m,
                            Titulo = "Mouse gamer inalámbrico",
                            UrlImagen = "https://picsum.photos/seed/mouse/400/300",
                            VendedorId = 1,
                            Version = 0
                        });
                });

            modelBuilder.Entity("SubastaYa.Api.Models.TransaccionLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BilleteraId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.ToTable("TransaccionesLedger");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 9, 3, 22, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            Monto = 150000m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            BilleteraId = 3,
                            Fecha = new DateTime(2026, 9, 3, 22, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            Monto = 200000m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 3,
                            BilleteraId = 4,
                            Fecha = new DateTime(2026, 9, 3, 22, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            Monto = 500m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 4,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 9, 6, 21, 54, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            Monto = 45000m,
                            SubastaId = 1,
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("SubastaYa.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vendedor@test.com",
                            FechaRegistro = new DateTime(2026, 9, 6, 22, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            Nombre = "Vendedor Demo",
                            PasswordHash = "demo-hash"
                        },
                        new
                        {
                            Id = 2,
                            Email = "comprador1@test.com",
                            FechaRegistro = new DateTime(2026, 9, 6, 22, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            Nombre = "Comprador Uno",
                            PasswordHash = "demo-hash"
                        },
                        new
                        {
                            Id = 3,
                            Email = "comprador2@test.com",
                            FechaRegistro = new DateTime(2026, 9, 6, 22, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            Nombre = "Comprador Dos",
                            PasswordHash = "demo-hash"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sinfondos@test.com",
                            FechaRegistro = new DateTime(2026, 9, 6, 22, 14, 44, 158, DateTimeKind.Utc).AddTicks(5547),
                            Nombre = "Sin Fondos",
                            PasswordHash = "demo-hash"
                        });
                });

            modelBuilder.Entity("SubastaYa.Api.Models.Billetera", b =>
                {
                    b.HasOne("SubastaYa.Api.Models.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("SubastaYa.Api.Models.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.Api.Models.Puja", b =>
                {
                    b.HasOne("SubastaYa.Api.Models.Usuario", "Comprador")
                        .WithMany("Pujas")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Api.Models.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.Api.Models.Subasta", b =>
                {
                    b.HasOne("SubastaYa.Api.Models.Categoria", "Categoria")
                        .WithMany("Subastas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Api.Models.Usuario", "Vendedor")
                        .WithMany("SubastasPublicadas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SubastaYa.Api.Models.TransaccionLedger", b =>
                {
                    b.HasOne("SubastaYa.Api.Models.Billetera", "Billetera")
                        .WithMany("Movimientos")
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Billetera");
                });

            modelBuilder.Entity("SubastaYa.Api.Models.Billetera", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SubastaYa.Api.Models.Categoria", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("SubastaYa.Api.Models.Subasta", b =>
                {
                    b.Navigation("Pujas");
                });

            modelBuilder.Entity("SubastaYa.Api.Models.Usuario", b =>
                {
                    b.Navigation("Billetera");

                    b.Navigation("Pujas");

                    b.Navigation("SubastasPublicadas");
                });
#pragma warning restore 612, 618
        }
    }
}
